AWSTemplateFormatVersion: "2010-09-09"
Description: This will install the deployment runner on the selected subnet. The organization id and key are unique to your account and used for authorization and communication with deployment servers.
Mappings:
  RegionMap:
    af-south-1:
      AMI: ami-0c39a41a810aa29f2
    ap-east-1:
      AMI: ami-031c72f4dd680ab91
    ap-northeast-1:
      AMI: ami-0c76d299e72176192
    ap-northeast-2:
      AMI: ami-05f383abd0269f22d
    ap-northeast-3:
      AMI: ami-03a24c9bb21f78dba
    ap-south-1:
      AMI: ami-026d60dca99a5ac54
    ap-south-2:
      AMI: ami-0f99fec80f37614f3
    ap-southeast-1:
      AMI: ami-0b9d27eb102c9f32f
    ap-southeast-2:
      AMI: ami-052f5845e525f2a29
    ap-southeast-3:
      AMI: ami-0def9cc1477f583eb
    ap-southeast-4:
      AMI: ami-0e2fd75f1df559d08
    ca-central-1:
      AMI: ami-0f72aaf1e4d7f3605
    eu-central-1:
      AMI: ami-08b4378b35f70d03c
    eu-central-2:
      AMI: ami-00fba9baab298d095
    eu-north-1:
      AMI: ami-06c18a256c715d3c5
    eu-south-1:
      AMI: ami-0309910379b63cd38
    eu-south-2:
      AMI: ami-0cbc6d29733c6aa48
    eu-west-1:
      AMI: ami-0bca9446f7c0ba062
    eu-west-2:
      AMI: ami-0a0e725d435985ad9
    eu-west-3:
      AMI: ami-02fee4a0d2dd7372e
    me-central-1:
      AMI: ami-0b5843a6943d1e9a3
    me-south-1:
      AMI: ami-0dc6e437aecc1bacd
    sa-east-1:
      AMI: ami-090eb5659d4e6371e
    us-east-1:
      AMI: ami-06a88052e3ac31bf0
    us-east-2:
      AMI: ami-0684647c89548bb1d
    us-west-1:
      AMI: ami-0c3cba4b252f21775
    us-west-2:
      AMI: ami-00c247b8613d444b8
Parameters:
  DeploymentRunnerSubnetId:
    ConstraintDescription: Should be present
    Description: Please select Subnet where the runner will be deployed.
    Type: AWS::EC2::Subnet::Id
  Key:
    AllowedPattern: ^[a-zA-Z0-9]+$
    ConstraintDescription: API key must only contain uppercase and lowercase letters and numbers
    Description: '[Do not update]. This is your unique prefilled token key identifier that is used for communication with deployment.io.'
    Type: String
  OrganizationID:
    AllowedPattern: ^[a-zA-Z0-9]+$
    ConstraintDescription: Organization ID must only contain uppercase and lowercase letters and numbers
    Description: '[Do not update]. This is your unique prefilled organization id.'
    Type: String
Resources:
  DeploymentEcsInstanceProfileamd:
    DependsOn:
      - DeploymentEcsInstanceRoleamd
    Properties:
      InstanceProfileName:
        Fn::Join:
          - '-'
          - - ecsInstanceProfileamd
            - Ref: OrganizationID
      Roles:
        - Ref: DeploymentEcsInstanceRoleamd
    Type: AWS::IAM::InstanceProfile
  DeploymentEcsInstanceRoleamd:
    Properties:
      AssumeRolePolicyDocument: |-
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      RoleName:
        Fn::Join:
          - '-'
          - - ecsInstanceRoleamd
            - Ref: OrganizationID
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role
  DeploymentRunnerASGamd:
    DependsOn:
      - DeploymentRunnerLaunchTemplateamd
    Properties:
      AutoScalingGroupName: deployment-runner-asg-amd
      DefaultInstanceWarmup: 5
      DesiredCapacity: "0"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: DeploymentRunnerLaunchTemplateamd
        Version:
          Fn::GetAtt:
            - DeploymentRunnerLaunchTemplateamd
            - LatestVersionNumber
      MaxSize: "2"
      MinSize: "0"
      VPCZoneIdentifier:
        - Ref: DeploymentRunnerSubnetId
    Type: AWS::AutoScaling::AutoScalingGroup
  DeploymentRunnerAwsControllerServiceamd:
    DependsOn:
      - DeploymentRunnerClusteramd
      - DeploymentRunnerAwsControllerTaskDefinitionamd
    Properties:
      Cluster:
        Fn::Join:
          - '-'
          - - deployment-runner-amd
            - Ref: OrganizationID
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      EnableECSManagedTags: false
      EnableExecuteCommand: false
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Ref: DeploymentRunnerSubnetId
      PropagateTags: TASK_DEFINITION
      SchedulingStrategy: REPLICA
      ServiceName: deployment-runner-aws-controller-amd
      Tags:
        - Key: Name
          Value: deployment-runner-aws-controller-amd
        - Key: created by
          Value: deployment.io
      TaskDefinition:
        Ref: DeploymentRunnerAwsControllerTaskDefinitionamd
    Type: AWS::ECS::Service
  DeploymentRunnerAwsControllerTaskDefinitionamd:
    DependsOn:
      - DeploymentRunnerTaskExecutionRoleamd
      - DeploymentRunnerTaskRoleamd
    Properties:
      ContainerDefinitions:
        - DisableNetworking: false
          Environment:
            - Name: Token
              Value:
                Ref: Key
            - Name: OrganizationID
              Value:
                Ref: OrganizationID
            - Name: Service
              Value: go.deployment.io:443
            - Name: DockerImage
              Value: docker.io/arorankit/deployment-runner-aws-controller-amd64:1
            - Name: Region
              Value:
                Ref: AWS::Region
            - Name: CpuArch
              Value: amd
            - Name: Memory
              Value: 6 GB
            - Name: ExecutionRoleArn
              Value:
                Ref: DeploymentRunnerTaskExecutionRoleamd
            - Name: TaskRoleArn
              Value:
                Ref: DeploymentRunnerTaskRoleamd
          Essential: true
          Image: docker.io/arorankit/deployment-runner-aws-controller-amd64:1
          Interactive: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: deployment-runner-aws-controller-logs-group-amd
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: "1"
          Name: deployment-runner-aws-controller-amd
          Privileged: false
          PseudoTerminal: false
          ReadonlyRootFilesystem: false
      Cpu: .25 vCPU
      ExecutionRoleArn:
        Ref: DeploymentRunnerTaskExecutionRoleamd
      Family: deployment-runner-aws-controller-amd
      Memory: 0.5 GB
      NetworkMode: awsvpc
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: deployment-runner-aws-controller-amd
        - Key: created by
          Value: deployment.io
      TaskRoleArn:
        Ref: DeploymentRunnerTaskRoleamd
    Type: AWS::ECS::TaskDefinition
  DeploymentRunnerCCamd:
    DependsOn:
      - DeploymentRunnerASGamd
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn:
          Ref: DeploymentRunnerASGamd
      Name: deployment-runner-capacity-provider-amd
      Tags:
        - Key: created by
          Value: deployment.io
        - Key: capacity provider
          Value: deployment-runner-capacity-provider-amd
    Type: AWS::ECS::CapacityProvider
  DeploymentRunnerClusteramd:
    DependsOn:
      - DeploymentRunnerCCamd
    Properties:
      CapacityProviders:
        - FARGATE
        - deployment-runner-capacity-provider-amd
      ClusterName:
        Fn::Join:
          - '-'
          - - deployment-runner-amd
            - Ref: OrganizationID
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::ECS::Cluster
  DeploymentRunnerLaunchTemplateamd:
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
              - DeploymentEcsInstanceProfileamd
              - Arn
        ImageId:
          Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - AMI
        InstanceType: m6a.large
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId:
              Ref: DeploymentRunnerSubnetId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: created by
                Value: deployment.io
              - Key: instance launch template
                Value: deployment-runner-template-amd
        UserData:
          Fn::Base64:
            Fn::Join:
              - "\n"
              - - '#!/bin/bash'
                - Fn::Join:
                    - ""
                    - - 'echo "ECS_CLUSTER='
                      - Fn::Join:
                          - '-'
                          - - 'deployment-runner-amd'
                            - Ref: OrganizationID
                      - '" >> /etc/ecs/ecs.config'
      LaunchTemplateName: deployment-runner-template-amd
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: created by
              Value: deployment.io
            - Key: launch template
              Value: deployment-runner-template-amd
      VersionDescription: launch template for deployment runner ec2 instance
    Type: AWS::EC2::LaunchTemplate
  DeploymentRunnerServiceamd:
    DependsOn:
      - DeploymentRunnerClusteramd
      - DeploymentRunnerTaskDefinitionamd
    Properties:
      CapacityProviderStrategy:
        - CapacityProvider: deployment-runner-capacity-provider-amd
          Weight: 1
      Cluster:
        Fn::Join:
          - '-'
          - - deployment-runner-amd
            - Ref: OrganizationID
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 0
      EnableECSManagedTags: false
      EnableExecuteCommand: false
      PropagateTags: TASK_DEFINITION
      SchedulingStrategy: REPLICA
      ServiceName: deployment-runner-amd
      Tags:
        - Key: Name
          Value: deployment-runner-amd
        - Key: created by
          Value: deployment.io
      TaskDefinition:
        Ref: DeploymentRunnerTaskDefinitionamd
    Type: AWS::ECS::Service
  DeploymentRunnerTaskDefinitionamd:
    DependsOn:
      - DeploymentRunnerTaskExecutionRoleamd
      - DeploymentRunnerTaskRoleamd
    Properties:
      ContainerDefinitions:
        - DisableNetworking: false
          Environment:
            - Name: Token
              Value:
                Ref: Key
            - Name: OrganizationID
              Value:
                Ref: OrganizationID
            - Name: Service
              Value: go.deployment.io:443
            - Name: DockerImage
              Value: docker.io/arorankit/deployment-runner-amd64:17
            - Name: Region
              Value:
                Ref: AWS::Region
            - Name: CpuArch
              Value: amd
            - Name: Memory
              Value: 6 GB
            - Name: ExecutionRoleArn
              Value:
                Ref: DeploymentRunnerTaskExecutionRoleamd
            - Name: TaskRoleArn
              Value:
                Ref: DeploymentRunnerTaskRoleamd
          Essential: true
          Image: docker.io/arorankit/deployment-runner-amd64:17
          Interactive: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: deployment-runner-logs-group-amd
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: "17"
          MountPoints:
            - ContainerPath: /var/run/docker.sock
              SourceVolume: docker-socket
            - ContainerPath: /tmp
              SourceVolume: temp
          Name: deployment-runner-amd
          Privileged: false
          PseudoTerminal: false
          ReadonlyRootFilesystem: false
      ExecutionRoleArn:
        Ref: DeploymentRunnerTaskExecutionRoleamd
      Family: deployment-runner-amd
      Memory: 6 GB
      NetworkMode: host
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value: deployment-runner-amd
        - Key: created by
          Value: deployment.io
      TaskRoleArn:
        Ref: DeploymentRunnerTaskRoleamd
      Volumes:
        - Host:
            SourcePath: /var/run/docker.sock
          Name: docker-socket
        - Host:
            SourcePath: /tmp
          Name: temp
    Type: AWS::ECS::TaskDefinition
  DeploymentRunnerTaskExecutionRoleamd:
    Properties:
      AssumeRolePolicyDocument: |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      RoleName:
        Fn::Join:
          - '-'
          - - ecsTaskExecutionRole-amd
            - Ref: OrganizationID
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role
  DeploymentRunnerTaskRoleamd:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition:
              ArnLike:
                aws:SourceArn:
                  Fn::Join:
                    - ""
                    - - 'arn:aws:ecs:'
                      - Ref: AWS::Region
                      - ':'
                      - Ref: AWS::AccountId
                      - :*
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
        Version: "2012-10-17"
      Description: This IAM Role is assigned to deployment runner task installed on your AWS account. At no point access is given to any other account or task.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudFrontFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:*
                Effect: Allow
                Resource:
                  - '*'
              - Action:
                  - iam:CreateServiceLinkedRole
                Condition:
                  StringLike:
                    iam:AWSServiceName: ecs.amazonaws.com
                Effect: Allow
                Resource:
                  - Fn::Join:
                      - ""
                      - - 'arn:aws:iam::'
                        - Ref: AWS::AccountId
                        - :role/ecs.amazonaws.com/*
            Version: "2012-10-17"
          PolicyName: deployment-runner-policy
      RoleName: deployment-runner-task-role-amd
      Tags:
        - Key: Name
          Value: deployment-runner-task-role-amd
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role