AWSTemplateFormatVersion: "2010-09-09"
Description: This will install the deployment runner on the selected subnet. The organization id and key are unique to your account and used for authorization and communication with deployment servers.
Mappings:
  RegionMap:
    af-south-1:
      AMI: ami-07a74725fbb49cb48
    ap-east-1:
      AMI: ami-002462b60f65e3932
    ap-northeast-1:
      AMI: ami-07c7a6df036bf6ecd
    ap-northeast-2:
      AMI: ami-0f3e2a61795a38ab9
    ap-northeast-3:
      AMI: ami-08d8b27a93a7466f0
    ap-south-1:
      AMI: ami-07bb9aa4e43a2d031
    ap-south-2:
      AMI: ami-0c954c4a8f788a01c
    ap-southeast-1:
      AMI: ami-0a01ee19565d9edbc
    ap-southeast-2:
      AMI: ami-03a88663b6e6e9690
    ap-southeast-3:
      AMI: ami-0e938fe88e51b9f45
    ap-southeast-4:
      AMI: ami-0fa88cb45b4ef5942
    ca-central-1:
      AMI: ami-0d3c363fb12838edf
    eu-central-1:
      AMI: ami-0a35d3bb530944416
    eu-central-2:
      AMI: ami-00d53d75eef59cce0
    eu-north-1:
      AMI: ami-0cc385dc8d1ab9e63
    eu-south-1:
      AMI: ami-0ac3f9e2a02f2c44d
    eu-south-2:
      AMI: ami-055cce68af553c66f
    eu-west-1:
      AMI: ami-081e22ecac78259a3
    eu-west-2:
      AMI: ami-066e88458207c8b25
    eu-west-3:
      AMI: ami-05f8b82b70cfa9d8c
    me-central-1:
      AMI: ami-05154de2f1a28669a
    me-south-1:
      AMI: ami-0df136cf732bd6145
    sa-east-1:
      AMI: ami-03a9b11afe0caa696
    us-east-1:
      AMI: ami-024cf340f2c79e44d
    us-east-2:
      AMI: ami-0824f066b0bab3eca
    us-west-1:
      AMI: ami-0a393caabb9a09860
    us-west-2:
      AMI: ami-08c89cb3053b529ec
Parameters:
  DeploymentRunnerSubnetId:
    ConstraintDescription: Should be present
    Description: Please select Subnet where the runner will be deployed.
    Type: AWS::EC2::Subnet::Id
  Key:
    AllowedPattern: ^[a-zA-Z0-9]+$
    ConstraintDescription: API key must only contain uppercase and lowercase letters and numbers
    Description: '[Do not update]. This is your unique prefilled token key identifier that is used for communication with deployment.io.'
    Type: String
  OrganizationID:
    AllowedPattern: ^[a-zA-Z0-9]+$
    ConstraintDescription: Organization ID must only contain uppercase and lowercase letters and numbers
    Description: '[Do not update]. This is your unique prefilled organization id.'
    Type: String
Resources:
  DeploymentEcsInstanceProfilelinuxamd:
    DependsOn:
      - DeploymentEcsInstanceRolelinuxamd
    Properties:
      InstanceProfileName:
        Fn::Join:
          - '-'
          - - ecsInstanceProfilelinuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Roles:
        - Ref: DeploymentEcsInstanceRolelinuxamd
    Type: AWS::IAM::InstanceProfile
  DeploymentEcsInstanceRolelinuxamd:
    Properties:
      AssumeRolePolicyDocument: |-
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      RoleName:
        Fn::Join:
          - '-'
          - - ecsInstanceRolelinuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role
  DeploymentRunnerASGlinuxamd:
    DependsOn:
      - DeploymentRunnerLaunchTemplatelinuxamd
    Properties:
      AutoScalingGroupName:
        Fn::Join:
          - '-'
          - - dr-asg-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      DefaultInstanceWarmup: 5
      DesiredCapacity: "0"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: DeploymentRunnerLaunchTemplatelinuxamd
        Version:
          Fn::GetAtt:
            - DeploymentRunnerLaunchTemplatelinuxamd
            - LatestVersionNumber
      MaxSize: "2"
      MinSize: "0"
      VPCZoneIdentifier:
        - Ref: DeploymentRunnerSubnetId
    Type: AWS::AutoScaling::AutoScalingGroup
  DeploymentRunnerAwsControllerServicelinuxamd:
    DependsOn:
      - DeploymentRunnerClusterlinuxamd
      - DeploymentRunnerAwsControllerTaskDefinitionlinuxamd
    Properties:
      Cluster:
        Fn::Join:
          - '-'
          - - dr-linuxamd
            - Ref: OrganizationID
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      EnableECSManagedTags: false
      EnableExecuteCommand: false
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Ref: DeploymentRunnerSubnetId
      PropagateTags: TASK_DEFINITION
      SchedulingStrategy: REPLICA
      ServiceName:
        Fn::Join:
          - '-'
          - - dr-aws-controller-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - dr-aws-controller-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
        - Key: created by
          Value: deployment.io
      TaskDefinition:
        Ref: DeploymentRunnerAwsControllerTaskDefinitionlinuxamd
    Type: AWS::ECS::Service
  DeploymentRunnerAwsControllerTaskDefinitionlinuxamd:
    DependsOn:
      - DeploymentRunnerTaskExecutionRolelinuxamd
      - DeploymentRunnerTaskRolelinuxamd
    Properties:
      ContainerDefinitions:
        - DisableNetworking: false
          Environment:
            - Name: Token
              Value:
                Ref: Key
            - Name: OrganizationID
              Value:
                Ref: OrganizationID
            - Name: Service
              Value: go.deployment.io:443
            - Name: DockerImage
              Value: docker.io/arorankit/deployment-runner-aws-controller-amd64:3
            - Name: DockerRunnerImage
              Value: docker.io/arorankit/deployment-runner-amd64:26
            - Name: Region
              Value:
                Ref: AWS::Region
            - Name: Memory
              Value: 6 GB
            - Name: ExecutionRoleArn
              Value:
                Ref: DeploymentRunnerTaskExecutionRolelinuxamd
            - Name: TaskRoleArn
              Value:
                Ref: DeploymentRunnerTaskRolelinuxamd
            - Name: AWSAccountID
              Value:
                Ref: AWS::AccountId
          Essential: true
          Image: docker.io/arorankit/deployment-runner-aws-controller-amd64:3
          Interactive: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: dr-aws-controller-logs-group-linuxamd
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: "3"
          Name:
            Fn::Join:
              - '-'
              - - dr-aws-controller-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
          Privileged: false
          PseudoTerminal: false
          ReadonlyRootFilesystem: false
      Cpu: .25 vCPU
      ExecutionRoleArn:
        Ref: DeploymentRunnerTaskExecutionRolelinuxamd
      Family:
        Fn::Join:
          - '-'
          - - dr-aws-controller-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Memory: 0.5 GB
      NetworkMode: awsvpc
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - dr-aws-controller-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
        - Key: created by
          Value: deployment.io
      TaskRoleArn:
        Ref: DeploymentRunnerTaskRolelinuxamd
    Type: AWS::ECS::TaskDefinition
  DeploymentRunnerCClinuxamd:
    DependsOn:
      - DeploymentRunnerASGlinuxamd
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn:
          Ref: DeploymentRunnerASGlinuxamd
      Name:
        Fn::Join:
          - '-'
          - - dr-capacity-provider-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: created by
          Value: deployment.io
        - Key: capacity provider
          Value:
            Fn::Join:
              - '-'
              - - dr-capacity-provider-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
    Type: AWS::ECS::CapacityProvider
  DeploymentRunnerClusterlinuxamd:
    DependsOn:
      - DeploymentRunnerCClinuxamd
    Properties:
      CapacityProviders:
        - FARGATE
        - Fn::Join:
            - '-'
            - - dr-capacity-provider-linuxamd
              - Ref: OrganizationID
              - Ref: AWS::Region
      ClusterName:
        Fn::Join:
          - '-'
          - - dr-linuxamd
            - Ref: OrganizationID
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::ECS::Cluster
  DeploymentRunnerLaunchTemplatelinuxamd:
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
              - DeploymentEcsInstanceProfilelinuxamd
              - Arn
        ImageId:
          Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - AMI
        InstanceType: m6a.large
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId:
              Ref: DeploymentRunnerSubnetId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: created by
                Value: deployment.io
              - Key: instance launch template
                Value:
                  Fn::Join:
                    - '-'
                    - - dr-template-linuxamd
                      - Ref: OrganizationID
                      - Ref: AWS::Region
        UserData:
          Fn::Base64:
            Fn::Join:
              - "\n"
              - - '#!/bin/bash'
                - Fn::Join:
                    - ""
                    - - 'echo "ECS_CLUSTER='
                      - Fn::Join:
                          - '-'
                          - - 'dr-linuxamd'
                            - Ref: OrganizationID
                      - '" >> /etc/ecs/ecs.config'
      LaunchTemplateName:
        Fn::Join:
          - '-'
          - - dr-template-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: created by
              Value: deployment.io
            - Key: launch template
              Value:
                Fn::Join:
                  - '-'
                  - - dr-template-linuxamd
                    - Ref: OrganizationID
                    - Ref: AWS::Region
      VersionDescription: launch template for deployment runner ec2 instance
    Type: AWS::EC2::LaunchTemplate
  DeploymentRunnerServicelinuxamd:
    DependsOn:
      - DeploymentRunnerClusterlinuxamd
      - DeploymentRunnerTaskDefinitionlinuxamd
    Properties:
      CapacityProviderStrategy:
        - CapacityProvider:
            Fn::Join:
              - '-'
              - - dr-capacity-provider-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
          Weight: 1
      Cluster:
        Fn::Join:
          - '-'
          - - dr-linuxamd
            - Ref: OrganizationID
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 0
      EnableECSManagedTags: false
      EnableExecuteCommand: false
      PropagateTags: TASK_DEFINITION
      SchedulingStrategy: REPLICA
      ServiceName:
        Fn::Join:
          - '-'
          - - dr-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - dr-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
        - Key: created by
          Value: deployment.io
      TaskDefinition:
        Ref: DeploymentRunnerTaskDefinitionlinuxamd
    Type: AWS::ECS::Service
  DeploymentRunnerTaskDefinitionlinuxamd:
    DependsOn:
      - DeploymentRunnerTaskExecutionRolelinuxamd
      - DeploymentRunnerTaskRolelinuxamd
    Properties:
      ContainerDefinitions:
        - DisableNetworking: false
          Environment:
            - Name: Token
              Value:
                Ref: Key
            - Name: OrganizationID
              Value:
                Ref: OrganizationID
            - Name: Service
              Value: go.deployment.io:443
            - Name: DockerImage
              Value: docker.io/arorankit/deployment-runner-amd64:26
            - Name: Region
              Value:
                Ref: AWS::Region
            - Name: Memory
              Value: 6 GB
            - Name: ExecutionRoleArn
              Value:
                Ref: DeploymentRunnerTaskExecutionRolelinuxamd
            - Name: TaskRoleArn
              Value:
                Ref: DeploymentRunnerTaskRolelinuxamd
            - Name: AWSAccountID
              Value:
                Ref: AWS::AccountId
          Essential: true
          Image: docker.io/arorankit/deployment-runner-amd64:26
          Interactive: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: dr-logs-group-linuxamd
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: "26"
          MountPoints:
            - ContainerPath: /var/run/docker.sock
              SourceVolume: docker-socket
            - ContainerPath: /tmp
              SourceVolume: temp
          Name:
            Fn::Join:
              - '-'
              - - dr-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
          Privileged: false
          PseudoTerminal: false
          ReadonlyRootFilesystem: false
      ExecutionRoleArn:
        Ref: DeploymentRunnerTaskExecutionRolelinuxamd
      Family:
        Fn::Join:
          - '-'
          - - dr-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Memory: 6 GB
      NetworkMode: host
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - dr-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
        - Key: created by
          Value: deployment.io
      TaskRoleArn:
        Ref: DeploymentRunnerTaskRolelinuxamd
      Volumes:
        - Host:
            SourcePath: /var/run/docker.sock
          Name: docker-socket
        - Host:
            SourcePath: /tmp
          Name: temp
    Type: AWS::ECS::TaskDefinition
  DeploymentRunnerTaskExecutionRolelinuxamd:
    Properties:
      AssumeRolePolicyDocument: |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      RoleName:
        Fn::Join:
          - '-'
          - - eTERole-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role
  DeploymentRunnerTaskRolelinuxamd:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Condition:
              ArnLike:
                aws:SourceArn:
                  Fn::Join:
                    - ""
                    - - 'arn:aws:ecs:'
                      - Ref: AWS::Region
                      - ':'
                      - Ref: AWS::AccountId
                      - :*
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
        Version: "2012-10-17"
      Description: This IAM Role is assigned to deployment runner task installed on your AWS account. At no point access is given to any other account or task.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudFrontFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:*
                Effect: Allow
                Resource:
                  - '*'
              - Action:
                  - iam:CreateServiceLinkedRole
                Condition:
                  StringLike:
                    iam:AWSServiceName: ecs.amazonaws.com
                Effect: Allow
                Resource:
                  - Fn::Join:
                      - ""
                      - - 'arn:aws:iam::'
                        - Ref: AWS::AccountId
                        - :role/ecs.amazonaws.com/*
            Version: "2012-10-17"
          PolicyName:
            Fn::Join:
              - '-'
              - - dr-policy-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
      RoleName:
        Fn::Join:
          - '-'
          - - dr-task-role-linuxamd
            - Ref: OrganizationID
            - Ref: AWS::Region
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - dr-task-role-linuxamd
                - Ref: OrganizationID
                - Ref: AWS::Region
        - Key: created by
          Value: deployment.io
    Type: AWS::IAM::Role